# Uncomment the next line to define a global platform for your project
# platform :ios, '13.1'

target 'RecipeSelector' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RecipeSelector
pod ‘SQLite.swift’, :git => ‘https://github.com/stephencelis/SQLite.swift.git’, :branch => ‘master’
end
